// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeyValueInput } from "./KeyValueInput";
import type { View } from "./View";

export type WasmInput = { "InputChanges": Array<KeyValueInput> } | { "AdvanceTo": bigint } | "StepUntilComplete" | { "CreateView": View };