// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeyValueOutput } from "./KeyValueOutput";

export type WasmOutput = { "Values": Array<KeyValueOutput> } | { "ViewResults": { view_key: string, values: Array<[string, number]>, } };